import { useEffect, useState } from "react";
import { Edit3, Eye, EyeOff, Image, Plus, Trash2, X } from "lucide-react";
import { toast } from "react-toastify";
import axiosInstance from "../lib/axios";

const configs = {
  banners: { label: "Hero banners", fields: [["eyebrow", "Eyebrow"], ["title", "Title"], ["description", "Description", "textarea"], ["image_url", "Image URL"], ["cta_label", "CTA label"], ["cta_url", "CTA URL"], ["sort_order", "Position", "number"]], defaults: { eyebrow: "New campaign", title: "", description: "", image_url: "", cta_label: "Explore", cta_url: "/products", sort_order: 0, is_active: true } },
  categories: { label: "Departments", fields: [["name", "Name"], ["slug", "URL slug"], ["description", "Description", "textarea"], ["image_url", "Image URL"], ["sort_order", "Position", "number"]], defaults: { name: "", slug: "", description: "", image_url: "", sort_order: 0, is_active: true } },
  offers: { label: "Offer cards", fields: [["kicker", "Kicker"], ["title", "Title"], ["description", "Description", "textarea"], ["promotion_code", "Promotion code"], ["cta_label", "CTA label"], ["cta_url", "CTA URL"], ["accent", "Accent (violet, sand, rose)"], ["sort_order", "Position", "number"]], defaults: { kicker: "Offer", title: "", description: "", promotion_code: "", cta_label: "Shop offer", cta_url: "/products", accent: "violet", sort_order: 0, is_active: true } },
  news: { label: "Editorial cards", fields: [["kicker", "Kicker"], ["title", "Title"], ["description", "Description", "textarea"], ["image_url", "Image URL"], ["cta_label", "CTA label"], ["cta_url", "CTA URL"], ["sort_order", "Position", "number"]], defaults: { kicker: "Journal", title: "", description: "", image_url: "", cta_label: "Discover", cta_url: "/products", sort_order: 0, is_active: true } },
};

const Storefront = () => {
  const [resource, setResource] = useState("banners"); const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [editing, setEditing] = useState(null); const [saving, setSaving] = useState(false);
  const config = configs[resource];
  const load = async () => { setLoading(true); try { const { data } = await axiosInstance.get(`/admin/storefront/${resource}`); setItems(data.items || []); } catch (error) { toast.error(error.response?.data?.message || "Could not load storefront content."); } finally { setLoading(false); } };
  useEffect(() => { setEditing(null); load(); }, [resource]);
  const openCreate = () => setEditing({ ...config.defaults });
  const save = async (event) => { event.preventDefault(); setSaving(true); try { const url = editing.id ? `/admin/storefront/${resource}/${editing.id}` : `/admin/storefront/${resource}`; const { data } = editing.id ? await axiosInstance.put(url, editing) : await axiosInstance.post(url, editing); toast.success(data.message); setEditing(null); load(); } catch (error) { toast.error(error.response?.data?.message || "Could not save storefront content."); } finally { setSaving(false); } };
  const remove = async (item) => { if (!window.confirm(`Delete “${item.title || item.name}”? This changes the live storefront.`)) return; try { const { data } = await axiosInstance.delete(`/admin/storefront/${resource}/${item.id}`); toast.success(data.message); load(); } catch (error) { toast.error(error.response?.data?.message || "Could not delete content."); } };
  return <div><header className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.24em] text-primary">Homepage CMS</p><h1 className="mt-2 font-display text-4xl font-semibold">Storefront studio</h1><p className="mt-2 text-sm text-stone">Manage the exact database content shown on the LUMERA home page.</p></div><button onClick={openCreate} className="admin-quick-link admin-quick-link-primary"><Plus className="h-3.5 w-3.5" /> Add {config.label.slice(0, -1)}</button></header>
    <div className="mb-6 flex gap-2 overflow-x-auto">{Object.entries(configs).map(([key, value]) => <button key={key} onClick={() => setResource(key)} className={`shrink-0 rounded-xl px-4 py-2.5 text-xs font-bold transition ${resource === key ? "bg-ink text-white" : "admin-surface text-stone"}`}>{value.label}</button>)}</div>
    {loading ? <div className="h-64 animate-pulse rounded-3xl bg-mist" /> : <div className="grid gap-4 md:grid-cols-2">{items.map((item) => <article key={item.id} className="admin-surface group overflow-hidden rounded-3xl"><div className="flex min-h-36 gap-4 p-4">{item.image_url ? <img src={item.image_url} alt="" className="h-24 w-24 shrink-0 rounded-2xl object-cover" /> : <div className="flex h-24 w-24 shrink-0 items-center justify-center rounded-2xl bg-mist text-primary"><Image className="h-6 w-6" /></div>}<div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div><p className="text-[10px] font-bold uppercase tracking-[.13em] text-primary">{item.eyebrow || item.kicker || item.slug || "Storefront"}</p><h2 className="mt-1 truncate font-display text-lg font-semibold">{item.title || item.name}</h2></div><span className={`rounded-full px-2 py-1 text-[9px] font-bold uppercase ${item.is_active ? "bg-emerald-100 text-emerald-700" : "bg-mist text-stone"}`}>{item.is_active ? "Live" : "Hidden"}</span></div><p className="mt-2 line-clamp-2 text-xs leading-relaxed text-stone">{item.description || item.cta_url || "No description"}</p><div className="mt-3 flex items-center justify-between"><span className="text-[10px] font-bold uppercase tracking-[.1em] text-stone">Position {item.sort_order}</span><div className="flex gap-1"><button onClick={() => setEditing({ ...item })} className="rounded-lg p-2 text-stone hover:bg-primary/10 hover:text-primary"><Edit3 className="h-4 w-4" /></button><button onClick={() => remove(item)} className="rounded-lg p-2 text-stone hover:bg-red-50 hover:text-red-600"><Trash2 className="h-4 w-4" /></button></div></div></div></div></article>)}{!items.length && <div className="admin-surface rounded-3xl p-12 text-center text-sm text-stone">No {config.label.toLowerCase()} yet. Create the first one.</div>}</div>}
    {editing && <div className="fixed inset-0 z-50 flex items-end bg-[#171233]/45 p-4 backdrop-blur-sm md:items-center md:justify-center"><form onSubmit={save} className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-[1.7rem] bg-fog p-6 shadow-2xl md:p-8"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-primary">Storefront editor</p><h2 className="mt-2 font-display text-2xl font-semibold">{editing.id ? "Edit" : "Add"} {config.label.slice(0, -1)}</h2></div><button type="button" onClick={() => setEditing(null)} className="rounded-xl bg-mist p-2"><X className="h-5 w-5" /></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2">{config.fields.map(([key, label, type]) => <label key={key} className={type === "textarea" ? "sm:col-span-2" : ""}><span className="text-[10px] font-bold uppercase tracking-[.14em] text-stone">{label}</span>{type === "textarea" ? <textarea required={key === "description"} rows="3" value={editing[key] || ""} onChange={(event) => setEditing({ ...editing, [key]: event.target.value })} className="mt-2 w-full rounded-xl border border-border/10 bg-white px-3 py-2.5 text-sm outline-none focus:border-primary" /> : <input required={!["kicker", "eyebrow", "promotion_code"].includes(key)} type={type || "text"} value={editing[key] || ""} onChange={(event) => setEditing({ ...editing, [key]: event.target.value })} className="mt-2 w-full rounded-xl border border-border/10 bg-white px-3 py-2.5 text-sm outline-none focus:border-primary" />}</label>)}<label className="flex items-center gap-2 text-sm font-medium"><input type="checkbox" checked={Boolean(editing.is_active)} onChange={(event) => setEditing({ ...editing, is_active: event.target.checked })} /> {editing.is_active ? <><Eye className="h-4 w-4 text-primary" /> Live on storefront</> : <><EyeOff className="h-4 w-4 text-stone" /> Hidden</>}</label></div><div className="mt-7 flex justify-end gap-3"><button type="button" onClick={() => setEditing(null)} className="px-4 py-3 text-xs font-bold uppercase tracking-[.12em] text-stone">Cancel</button><button disabled={saving} className="admin-quick-link admin-quick-link-primary">{saving ? "Saving" : "Save changes"}</button></div></form></div>}
  </div>;
};
export default Storefront;
