import { useEffect, useState } from "react";
import { Check, LocateFixed, MapPin, Pencil, Plus, Star, Trash2 } from "lucide-react";
import { toast } from "react-toastify";
import axiosInstance from "../../lib/axios";
import { requestDeliveryLocation } from "../../lib/location";

const blank = { label: "Home", recipient_name: "", phone: "", address: "", city: "", state: "", emirate: "", country: "United Arab Emirates", pincode: "", latitude: "", longitude: "", is_default: false };
const emirates = ["Abu Dhabi", "Dubai", "Sharjah", "Ajman", "Umm Al Quwain", "Ras Al Khaimah", "Fujairah"];

// Account-owned addresses are persisted in user_addresses and are independent of past order snapshots.
const AddressBook = ({ onSelect }) => {
  const [addresses, setAddresses] = useState([]);
  const [form, setForm] = useState(blank);
  const [editingId, setEditingId] = useState(null);
  const [open, setOpen] = useState(false);
  const [saving, setSaving] = useState(false);
  const [locating, setLocating] = useState(false);

  const load = async () => { try { const { data } = await axiosInstance.get("/address"); setAddresses(data.addresses || []); } catch { setAddresses([]); } };
  useEffect(() => { load(); }, []);
  const change = (event) => { const { name, value, checked, type } = event.target; setForm((valueBefore) => ({ ...valueBefore, [name]: type === "checkbox" ? checked : value })); };
  const edit = (address) => { setEditingId(address.id); setForm({ ...blank, ...address, latitude: address.latitude || "", longitude: address.longitude || "" }); setOpen(true); };
  const usePin = async () => { setLocating(true); try { const location = await requestDeliveryLocation(); setForm((previous) => ({ ...previous, address: location.address || previous.address, city: location.city || previous.city, state: location.emirate || previous.state, emirate: emirates.includes(location.emirate) ? location.emirate : previous.emirate, country: location.country || previous.country, latitude: location.latitude, longitude: location.longitude })); toast.success("Pin added. Check the address before saving."); } catch (error) { toast.info(error.message || "Location could not be found."); } finally { setLocating(false); } };
  const submit = async (event) => { event.preventDefault(); setSaving(true); try { const { data } = editingId ? await axiosInstance.put(`/address/${editingId}`, form) : await axiosInstance.post("/address", form); toast.success(data.message); setOpen(false); setEditingId(null); setForm(blank); await load(); } catch (error) { toast.error(error.response?.data?.message || "Could not save address."); } finally { setSaving(false); } };
  const remove = async (id) => { if (!window.confirm("Remove this saved address?")) return; try { const { data } = await axiosInstance.delete(`/address/${id}`); toast.success(data.message); await load(); } catch (error) { toast.error(error.response?.data?.message || "Could not remove address."); } };
  const makeDefault = async (id) => { try { const { data } = await axiosInstance.put(`/address/${id}/default`); toast.success(data.message); await load(); } catch (error) { toast.error(error.response?.data?.message || "Could not update default address."); } };

  return <section className="border-t border-border/10 pt-7"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-primary">Delivery book</p><h3 className="mt-1 font-display text-lg font-semibold">Home, Office & more</h3></div><button type="button" onClick={() => { setEditingId(null); setForm(blank); setOpen(!open); }} className="rounded-xl bg-ink p-2 text-white"><Plus className="h-4 w-4" /></button></div><p className="mt-2 text-xs leading-relaxed text-stone">Saved addresses are private to your account and can be used at checkout.</p>
    <div className="mt-4 space-y-3">{addresses.map((address) => <div key={address.id} className="rounded-2xl border border-border/10 bg-white/55 p-3"><div className="flex gap-3"><MapPin className="mt-0.5 h-4 w-4 shrink-0 text-primary" /><button type="button" onClick={() => onSelect?.(address)} className="min-w-0 flex-1 text-left"><p className="text-sm font-semibold">{address.label}{address.is_default && <span className="ml-2 text-[10px] font-bold uppercase tracking-[.12em] text-primary">Default</span>}</p><p className="mt-1 text-xs leading-relaxed text-stone">{address.address}, {address.city} · {address.emirate}</p></button><div className="flex items-start gap-1"><button type="button" onClick={() => edit(address)} className="rounded-lg p-1.5 text-stone hover:bg-mist"><Pencil className="h-3.5 w-3.5" /></button><button type="button" onClick={() => remove(address.id)} className="rounded-lg p-1.5 text-stone hover:bg-red-50 hover:text-red-600"><Trash2 className="h-3.5 w-3.5" /></button></div></div>{!address.is_default && <button type="button" onClick={() => makeDefault(address.id)} className="mt-3 inline-flex items-center gap-1 text-[10px] font-bold uppercase tracking-[.12em] text-primary"><Star className="h-3.5 w-3.5" /> Set default</button>}</div>)}{!addresses.length && !open && <p className="rounded-2xl bg-mist/60 p-4 text-xs text-stone">No saved delivery addresses yet.</p>}</div>
    {open && <form onSubmit={submit} className="mt-4 space-y-3 rounded-2xl border border-primary/15 bg-primary/[.035] p-4"><div className="flex gap-2"><select name="label" value={form.label} onChange={change} className="flex-1 rounded-xl border border-border/10 bg-white px-3 py-2 text-sm"><option>Home</option><option>Office</option><option>Other</option></select><button type="button" onClick={usePin} disabled={locating} className="inline-flex items-center gap-1 rounded-xl border border-primary/20 px-3 text-[10px] font-bold uppercase tracking-[.1em] text-primary"><LocateFixed className={`h-3.5 w-3.5 ${locating ? "animate-spin" : ""}`} /> Pin</button></div><div className="grid grid-cols-2 gap-3"><input required name="recipient_name" value={form.recipient_name} onChange={change} placeholder="Recipient name" className="rounded-xl border border-border/10 bg-white px-3 py-2 text-sm" /><input required name="phone" value={form.phone} onChange={change} placeholder="Phone" className="rounded-xl border border-border/10 bg-white px-3 py-2 text-sm" /></div><input required name="address" value={form.address} onChange={change} placeholder="Building, street, area" className="w-full rounded-xl border border-border/10 bg-white px-3 py-2 text-sm" /><div className="grid grid-cols-2 gap-3"><input required name="city" value={form.city} onChange={change} placeholder="City" className="rounded-xl border border-border/10 bg-white px-3 py-2 text-sm" /><select required name="emirate" value={form.emirate} onChange={(event) => { change(event); setForm((previous) => ({ ...previous, state: event.target.value })); }} className="rounded-xl border border-border/10 bg-white px-3 py-2 text-sm"><option value="">Emirate</option>{emirates.map((emirate) => <option key={emirate}>{emirate}</option>)}</select></div><div className="grid grid-cols-2 gap-3"><input required name="pincode" value={form.pincode} onChange={change} placeholder="Postal code" className="rounded-xl border border-border/10 bg-white px-3 py-2 text-sm" /><label className="flex items-center gap-2 text-xs text-stone"><input type="checkbox" name="is_default" checked={form.is_default} onChange={change} /> Default address</label></div><button disabled={saving} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-primary py-2.5 text-[10px] font-bold uppercase tracking-[.14em] text-white"><Check className="h-3.5 w-3.5" />{saving ? "Saving" : editingId ? "Save changes" : "Save address"}</button></form>}</section>;
};
export default AddressBook;
