// Gemini is asked only to choose catalogue IDs. The server always returns its own
// database rows, never arbitrary product data generated by a model.
export async function getAIRecommendation(userPrompt, products) {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) throw new Error("Gemini AI search is not configured.");

  const model = process.env.GEMINI_MODEL || "gemini-2.0-flash";
  const catalogue = products.map((product) => ({
    id: product.id,
    name: product.name,
    description: product.description,
    category: product.category,
    price: product.price,
    ratings: product.ratings,
    stock: product.stock,
  }));

  const response = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,
    {
      method: "POST",
      headers: { "Content-Type": "application/json", "x-goog-api-key": apiKey },
      body: JSON.stringify({
        contents: [{ parts: [{ text: `You are an ecommerce product finder. Customer request: ${JSON.stringify(userPrompt)}\n\nAvailable catalogue: ${JSON.stringify(catalogue)}\n\nReturn only JSON in exactly this shape: {"productIds":["id-1","id-2"]}. Choose up to 12 IDs from the catalogue that best satisfy the request. Never invent IDs.` }] }],
        generationConfig: { responseMimeType: "application/json", temperature: 0.2 },
      }),
    }
  );

  if (!response.ok) {
    const detail = await response.text();
    throw new Error(`Gemini request failed (${response.status}): ${detail.slice(0, 180)}`);
  }

  const data = await response.json();
  const text = data?.candidates?.[0]?.content?.parts?.[0]?.text?.trim();
  if (!text) throw new Error("Gemini returned no search results.");

  let payload;
  try { payload = JSON.parse(text.replace(/```json|```/g, "").trim()); }
  catch { throw new Error("Gemini returned an invalid search response."); }

  const wanted = new Set((payload?.productIds || []).map(String));
  return products.filter((product) => wanted.has(String(product.id)));
}
